#pragma once

#define MOUNT_POINT "/sdcard"

#define MOUNT_FILE_TRANSF_SIZE_LIMIT 4096
#define MOUNT_FILE_ALLOC_SIZE_EACH 512
#define MOUNT_FILE_MAX_OPEN_FILES_AT_ONCE 3
#define MOUNT_FILE_SPEED_KHZ 40000

#define MOUNT_FILE_PIN_MISO GPIO_NUM_19
#define MOUNT_FILE_PIN_MOSI GPIO_NUM_23
#define MOUNT_FILE_PIN_CLK  GPIO_NUM_18
#define MOUNT_FILE_PIN_CS   GPIO_NUM_5