#pragma once

#include "printer.hpp"
#include "sd_card.hpp"
#include "memory_file.hpp"
#include "memory_json.hpp"
#include "led_control.hpp"
#include "tasker.hpp"
#include "delayed_tasker.hpp"
#include "discord/core.hpp"
#include "discord/raw/gateway.hpp"
#include "discord/raw/http_interface.hpp"
#include "discord/raw/time_iso.hpp"
#include "discord/gateway/attachment.hpp"
#include "discord/gateway/channel.hpp"
#include "discord/gateway/embed.hpp"
#include "discord/gateway/emoji.hpp"
#include "discord/gateway/guild.hpp"
#include "discord/gateway/interaction.hpp"
#include "discord/gateway/member.hpp"
#include "discord/gateway/message.hpp"
#include "discord/gateway/presence.hpp"
#include "discord/gateway/reaction.hpp"
#include "discord/gateway/role.hpp"
#include "discord/gateway/user.hpp"

// This file include everything.